### ISSUE TITLE
Avoid `node-red-` package from being created

### ISSUE THREAD

**Issue by gorenje** [Steveorevo/node-maker#9]
Hi There!

First thing I did was to create a flow without a node name. Inject then caused a package to be created by the name of `node-red-`.

I put in a fix into the start-node subflow (in the function node):

```javascript
msg.node_name = env.get('node_name');

/* crash and burn if name not defined */
if (!msg.node_name || msg.node_name=="") {
    node.error(("node name not given"), msg);
    return
}

msg.node_version = env.get('node_version');
msg.node_description = env.get('node_description');
...
```

Great idea, btw - strangely I also started working on the similar [idea](https://flows.nodered.org/node/@gregoriusrippenstein/node-red-contrib-nodedev) but without the designing the UI components. I've taken a slightly different approach by representing an entire node package in Node-RED as nodes.

**Comment by Steveorevo** [comment]
Excellent, I've incorporated your suggestion to appear in next release.
